repos:
    - repo: https://github.com/python/black
      rev: 23.1.0
      hooks:
          - id: black
            args: [--target-version=py310]
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.254
      hooks:
          - id: ruff
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.6
      hooks:
          - id: prettier
            args: ["--ignore-path=.prettierignore"]
    - repo: https://github.com/econchick/interrogate
      rev: 1.5.0
      hooks:
          - id: interrogate
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
